### ISSUE TITLE
Update homepage header/footer

### ISSUE THREAD

**Issue by lucasmarcondes** [ASWWU-Web/homepage#69]
Sorry for the lack of a template. Here are some things that should be updated:

### Change
- Modify Collegian URL to https://collegian.xyz in the footer
- Modify Service Day URL to https://www.wallawalla.edu/campus-life/center-for-humanitarian-engagement/volunteer/service-day-2019/ in the footer
- Move the location "Diversity & Wellness" in the correct alphabetical order under the nav bar under "Departments"

### Remove
- Take out the "Pray it Further" link on footer

### Add
- Add the ASWWU Video Youtube channel to the social media section in the footer

Thanks for your hard work everyone!

**Comment by nick97eagles** [comment]
Pull request is open #71, and waiting for verification that the collegian link is correct.

**Comment by ermsdev** [comment]
Merged and Deployed, thanks Nick!
