### ISSUE TITLE
Fix ASWWU Forum Message Submissions

### ISSUE THREAD

**Issue by lucasmarcondes** [ASWWU-Web/homepage#70]
When sending a message through the ASWWU Forum, just above the footer, messages are not sending to ASWWU Administration. The "Loading..." label doesn't change.

I've also checked the aswwu.pres@wallawalla.edu email when sending it to President and there were no emails sent through the homepage.

**Comment by ermsdev** [comment]
@octagonprogramming I didn't mess around with it, but I was looking at this and think it is an issue with how we're using the request service.

There's a homepage request service with a method that returns an observable. In the forum component it looks like we call that method, but don't subscribe to the observable. A request isn't made until the observable is subscribed to. You can look at requests in other projects, like elections to see examples of this.

**Comment by stacmi** [comment]
you were correct that there was no subscribe method. added this

**Comment by lucasmarcondes** [comment]
Thanks for your hard work! I'm going to go ahead and close this issue.

**Comment by ermsdev** [comment]
this is now tested and deployed
